[package]
name = "crccheck"
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com>"]
edition = "2018"
description = "Implementation of the Saltpack format in Rust"
documentation = "https://docs.rs/saltpack"
homepage = "https://github.com/dnaka91/saltpack-rs"
repository = "https://github.com/dnaka91/saltpack-rs"
readme = "README.md"
keywords = ["cli", "crc", "utility"]
categories = ["command-line-utilities"]
license = "MIT OR Apache-2.0"

[dependencies]
colored = "1.9.0"
crc32fast = "1.2.0"
crossbeam-utils = "0.7.0"
failure = "0.1.6"
num_cpus = "1.11.1"
structopt = "0.3.5"
threadpool = "1.7.1"

[profile.release]
lto = true
panic = "abort"
